# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: bikeshare app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install pip dependencies
      run: python -m pip install --upgrade pip
    - name: Install test requirements dependencies
      run: pip install -r requirements/requirements.txt
    - name: Train and save pipeline
      run: python bikeshare_model/pipeline.py